//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.ServicioWeb {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWeb.BDSoap")]
    public interface BDSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getContribuyentes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getContribuyentes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getContribuyentes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getContribuyentesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getComprobantes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getComprobantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getComprobantes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getComprobantesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BDSoapChannel : UI.ServicioWeb.BDSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BDSoapClient : System.ServiceModel.ClientBase<UI.ServicioWeb.BDSoap>, UI.ServicioWeb.BDSoap {
        
        public BDSoapClient() {
        }
        
        public BDSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BDSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getContribuyentes() {
            return base.Channel.getContribuyentes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getContribuyentesAsync() {
            return base.Channel.getContribuyentesAsync();
        }
        
        public System.Data.DataSet getComprobantes() {
            return base.Channel.getComprobantes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getComprobantesAsync() {
            return base.Channel.getComprobantesAsync();
        }
    }
}
